# Site settings
title: Your blog title
name: Your name
description: Your blog description
#baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://embedding.ai" # the base hostname & protocol for your site e.g. http://materializeblog.com
google_analytics: ""

# User settings
profile_img_url: http://materializecss.com/res/materialize.svg
username: username
user_description: Write here a brief description about you.
email: username@gmail.com
github_username:  username
fb_username: username
twitter_username: username
instagram_username: username
linkedin_username: username
disqus_username: username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
#plugins:
#    - jemoji

# sass
sass:
  sass_dir: '_sass'
  style: compressed

#links
links:
  - title: Home
    url: "https://embedding.ai"
    external: true
  - title: Blog
    url: /#blog
  - title: Tags
    url: /#tags

remote_theme: victorpre/materialize-jekyll