# Site settings
name: Vithursan Thangarasa
title: Vithursan Thangarasa | Machine Learning Researcher
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://embedding.ai/
baseurl: ""
email: vithursan.thangarasa@gmail.com
cover: https://embedding.ai/img/og.png
logo: https://embedding.ai/img/emojis/technologist.png
resume: https://embedding.ai/resume.pdf
social:
  - title: email
    url: mailto:vithursan.thangarasa@gmail.com
  - title: twitter
    url: https://twitter.com/vthangarasa
  - title: instagram
    url: https://instagram.com/vithursant19
  - title: github
    url: https://github.com/vithursant
  - title: linkedin
    url: https://www.linkedin.com/in/vithursant

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap