# Use this file to control the main attributes of the website

# You
name: Vithursan Thangarasa

# Title for your site as it will appear in google
# e.g. Resume, Curriculum Vitae, Work History
title: Vithursan Thangarasa

# SEO description
description: Digital resume for Vithursan Thangarasa, AI practioner and engineer in Toronto, Canada.

# URL of this resume
url: 'https://vithursant.github.io'

# URL of your personal website (make same as URL if you don't have one)
personal: 'http://www.vithursant.com'

# these should be pretty self-explanatory :-P
email: vithursant.thangarasa@gmail.com
#twitter: 
linkedin: vithursant

# Show this in the footer
copyright: All rights reserved.

# What should the navigation be called?
navigation: navigation

# Google analytics ID: UA-XXXXX-X
analytics: UA-104881273-1

# Jekyll assets gem
assets:
  dirname: assets
  baseurl: /assets/
  css_compressor: yui
  js_compressor: yui
  cachebust: hard
  cache: false
  gzip: nil # Cloudflare will do this
  sources:
    - _assets/javascripts
    - _assets/stylesheets

# Files in this repo that we don't want to go to the web
exclude: [
  'scss',
  '*.rb',
  '*.yml', 
  'vendor', 
  'Gemfile', 
  'Gemfile.lock',
  '*.sh',
  'README.md',
  'LICENSE.md',
]
